'use client';
import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { summarizeArticle } from '@/ai/flows/summarize-article';
import { LoadingSpinner } from '../shared/loading-spinner';
import { Alert, AlertDescription, AlertTitle } from '../ui/alert';
import { Terminal } from 'lucide-react';

interface AiSummaryProps {
  articleUrl: string;
  isOpen: boolean;
  setIsOpen: (isOpen: boolean) => void;
}

export default function AiSummary({ articleUrl, isOpen, setIsOpen }: AiSummaryProps) {
  const [summary, setSummary] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleOpenChange = async (open: boolean) => {
    setIsOpen(open);
    if (open && !summary) {
      setIsLoading(true);
      setError('');
      try {
        const result = await summarizeArticle({ articleUrl });
        setSummary(result.summary);
      } catch (e) {
        console.error(e);
        setError('Could not generate summary. The AI model may be unavailable or the article could not be accessed.');
      } finally {
        setIsLoading(false);
      }
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="font-headline">AI Summary</DialogTitle>
          <DialogDescription>A concise summary of the article generated by AI.</DialogDescription>
        </DialogHeader>
        <div className="mt-4">
          {isLoading && (
            <div className="flex items-center justify-center h-32">
              <LoadingSpinner className="h-8 w-8" />
            </div>
          )}
          {error && (
            <Alert variant="destructive">
                <Terminal className="h-4 w-4" />
                <AlertTitle>Error</AlertTitle>
                <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}
          {summary && <p className="text-sm text-foreground leading-relaxed whitespace-pre-wrap">{summary}</p>}
        </div>
      </DialogContent>
    </Dialog>
  );
}
